### ISSUE TITLE
Data not updated if app is minimized while loading

### ISSUE THREAD

**Issue by khanhbkqt** [mohamad-amin/CleanTvMaze#2]
I also have this problem on my real project.
The onDetach is called when activity onStop(), so after data is loaded. The view not updated.
I fixed it by adding variables on check onAttach of presenter.
But it seems take a lot work, if the presenter has many works to do.

Do you have any solutions?

**Comment by mohamad-amin** [comment]
Sorry for answering too late.

Although the presenter is cached by the EasyMVP library, in this project we don't save any states to resume the flow of data and update the view after it has been reattached to the presenter.

For this purpose, we should create a kind of state machine to know the state we were in before the view got detached and resume from that state after it has been reattached to the cached presenter (minimization of the app in your question is the process of detaching and then reattaching the view).

I wanted to showcase the use of EasyMVP library here in this project so I didn't get into details on implementing that state machine to completely survive any change that causes view detachments and attachments. But I'm not saying that I won't create such a sample using the EasyMVP library that survives the configuration changes, I may create some more detailed samples if I happen to have some time in the coming weeks.

In case you want to see a detailed approach of saving and restoring the state of presenters (not necessarily using EasyMVP library) you can see this sample project:
https://github.com/GauravChaddha1996/MVP-Loader-Example
